# Generated by Django 4.1 on 2022-08-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Post_category',
            field=models.CharField(choices=[('AMATEUR', 'amateur'), ('ANAL', 'anal'), ('ASIAN', 'asian'), ('BDSM', 'bdsm'), ('BLONDE', 'blonde'), ('BRUNETTE', 'brunette'), ('CREAMPIE', 'creampie'), ('CUMSHOT', 'cumshot'), ('FISTING', 'fisting'), ('GANGBANG', 'gangbang'), ('GERMAN', 'german'), ('INDIAN', 'indian'), ('LATINA', 'latina'), ('LESBIAN', 'lesbian'), ('MILF', 'milf'), ('REDHEAD', 'redhead'), ('SOLO', 'solo'), ('SQUIRTING', 'squirting'), ('TEEN', 'teen')], default='', max_length=10),
        ),
    ]
