# Generated by Django 4.1 on 2022-08-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_content_post_keywords_post_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
